title: "Sharon Shen"
email: "tanglin150@gmail.com"
description: >-
  Strategic Key Account Manager | Analytics Leader | 6+ Years in Ad Tech & Export Growth
baseurl: "/modern-resume"
url: "https://sharon0611.github.io"
github_username: sharon0611

theme: "modern-resume-theme"

personal_links:
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/your-profile" # 替换为你的真实 LinkedIn 链接
  - title: "GitHub"
    url: "https://github.com/sharon0611"
  - title: "Email"
    url: "mailto:tanglin150@gmail.com"
